#!/bin/bash
# script untuk menginstal BANK CBA

if [[ $EUID != 0 ]]; then
    echo "Silahkan jalankan sebagai root."
    exit 1   
else
    read -p "Apakah Anda mau menginstal BANK CBA [iya/tidak]: " nanya
        if [[ $nanya == "iya" ]]; then
            echo "sedang menginstal BANK CBA."
            sleep 3
            chmod +x bank_cba
            mv bank_cba /usr/bin
            echo "BANK CBA berhasil diinstal."
            sleep 3
            echo "Untuk menjalankannya ketikkan perintah 'bank_cba'."
            exit 0
        elif [[ $nanya == "tidak" ]]; then
            exit 0
        else
            echo "Masukkan salah."
            exit 1
        fi
fi
